name: Daily Commit

on:
  schedule:
    # Runs at 17:30 UTC every day (which is 11:00 PM IST)
    - cron: '40 17 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug information
      run: |
        echo "Current working directory: $(pwd)"
        echo "List of files in the directory:"
        ls -la

    - name: Check git status
      run: |
        git status
        git branch

    - name: Add a commit to the repository
      run: |
        date > date.txt
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '22f1001316@ds.study.iitm.ac.in'
        git add date.txt
        git commit -m 'Daily commit'
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
