name: Daily Commit

on:
  schedule:
    # Runs at 12:00 UTC every day (adjust the time as needed)
    - cron: '0 12 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add a commit to the repository
      run: |
        date > date.txt
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '22f1001316@ds.study.iitm.ac.in'
        git add date.txt
        git commit -m 'Daily commit'
        git push origin HEAD
