name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 22f1001316@ds.study.iitm.ac.in
        run: echo "Hello, world!"
